# Generated by Django 5.1.15 on 2026-09-21 15:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='código único')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True, verbose_name='número de carnet')),
                ('tipo', models.CharField(choices=[('empleado', 'Empleado'), ('visitante', 'Visitante'), ('contratista', 'Contratista')], default='empleado', max_length=15, verbose_name='tipo')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('generado', 'Generado')], default='pendiente', max_length=10, verbose_name='estado')),
                ('plantilla', models.CharField(blank=True, default='default', max_length=50, verbose_name='plantilla / diseño')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carnets', to='personas.empleado', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'carnet',
                'verbose_name_plural': 'carnets',
                'ordering': ['-creado'],
            },
        ),
    ]
