# Generated by Django 5.1.15 on 2026-10-06 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCarnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(db_index=True, max_length=20, verbose_name='cédula')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='cargo')),
                ('departamento', models.CharField(blank=True, max_length=150, verbose_name='departamento')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='fecha de generación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'carnet generado',
                'verbose_name_plural': 'historial de carnets generados',
                'ordering': ['-creado'],
            },
        ),
    ]
