# Generated by Django 5.1.15 on 2026-10-06 19:56

import shutil
from django.db import migrations, models
import os
from django.conf import settings


def crear_plantilla_default(apps, schema_editor):
    Plantilla = apps.get_model('carnets', 'Plantilla')
    # Copiar el archivo PPTX existente a media/plantillas/
    src = os.path.join(settings.BASE_DIR, 'credencialfundacion.pptx')
    dst_dir = os.path.join(settings.MEDIA_ROOT, 'plantillas')
    os.makedirs(dst_dir, exist_ok=True)
    dst = os.path.join(dst_dir, 'credencialfundacion.pptx')
    if not os.path.exists(dst):
        shutil.copy2(src, dst)
    # Crear la plantilla predeterminada activa
    # Importante: el nombre guardado debe ser relativo a MEDIA_ROOT,
    # nunca una ruta absoluta (rompe archivo.url).
    Plantilla.objects.get_or_create(
        nombre='Predeterminada',
        defaults={
            'archivo': os.path.join('plantillas', 'credencialfundacion.pptx'),
            'activa': True,
            'descripcion': 'Plantilla por defecto (credencialfundacion.pptx)'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0002_historialcarnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('archivo', models.FileField(upload_to='plantillas/', verbose_name='archivo PPTX')),
                ('activa', models.BooleanField(default=False, help_text='Marca la plantilla que se usará al generar carnets automáticamente', verbose_name='activa')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'plantilla de carnet',
                'verbose_name_plural': 'plantillas de carnet',
                'ordering': ['-activa', 'nombre'],
            },
        ),
        migrations.RunPython(crear_plantilla_default),
    ]
