# Generated by Django 5.1.15 on 2026-10-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0003_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='plantillas/', verbose_name='archivo PPTX'),
        ),
    ]
