# Generated by Django 5.1.15

import os

from django.conf import settings
from django.db import migrations


def corregir_rutas(apps, schema_editor):
    """Normaliza el campo archivo a rutas relativas a MEDIA_ROOT.

    La migración 0003 guardó una ruta absoluta (p. ej.
    /home/.../media/plantillas/credencialfundacion.pptx), lo que rompía
    archivo.url (/media//home/... -> 404). El nombre debe quedar como
    plantillas/credencialfundacion.pptx.
    """
    Plantilla = apps.get_model('carnets', 'Plantilla')
    media_root = str(settings.MEDIA_ROOT)
    for plantilla in Plantilla.objects.all():
        nombre = (plantilla.archivo.name or '').strip()
        if not nombre or not os.path.isabs(nombre):
            continue
        if nombre.startswith(media_root):
            rel = nombre[len(media_root):].lstrip('/')
        else:
            rel = os.path.basename(nombre)
        plantilla.archivo.name = rel
        plantilla.save(update_fields=['archivo'])


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0004_alter_plantilla_archivo'),
    ]

    operations = [
        migrations.RunPython(corregir_rutas, migrations.RunPython.noop),
    ]