# Generated by Django 5.1.15 on 2026-10-08 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0005_corrige_ruta_archivo_plantilla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='razón social / nombre jurídico'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='teléfono'),
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='nombre completo')),
                ('documento', models.CharField(blank=True, max_length=32, verbose_name='documento (cédula / RIF)')),
                ('cargo', models.CharField(blank=True, max_length=255, verbose_name='cargo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_carnets/', verbose_name='foto')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='código público (QR)')),
                ('origen', models.CharField(choices=[('siglas', 'Base de datos (SIGLAS)'), ('manual', 'Ingreso manual')], default='manual', editable=False, max_length=10, verbose_name='origen')),
                ('ci_origen', models.CharField(blank=True, editable=False, max_length=20, verbose_name='cédula de origen (SIGLAS)')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'credencial (carnet)',
                'verbose_name_plural': 'credenciales / carnets',
                'ordering': ['-creado'],
                'permissions': [('ver_carnets', 'Puede consultar los datos de los carnets'), ('editar_imprimir_carnets', 'Puede editar la información e imprimir carnets'), ('crear_carnet_manual', 'Puede crear carnets con datos manuales')],
            },
        ),
    ]
