# Generated by Django 5.1.15 on 2026-09-21 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'Solo letras, números y guiones.')], verbose_name='número de documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellido')),
                ('cargo', models.CharField(choices=[('ASISTENTE ADMINISTRATIVO', 'Asistente Administrativo'), ('SECRETARIA', 'Secretaria'), ('DIRECTOR', 'Director(a)'), ('ANALISTA', 'Analista'), ('TECNICO', 'Técnico(a)'), ('GUARDIA', 'Guardia'), ('MENSAJERO', 'Mensajero'), ('OTRO', 'Otro')], max_length=100, verbose_name='cargo')),
                ('departamento', models.CharField(choices=[('DIRECCION DE ADMINISTRACION', 'Dirección de Administración'), ('DIRECCION GENERAL DE OFICINAS REGIONALES', 'Dirección General de Oficinas Regionales'), ('RECURSOS HUMANOS', 'Recursos Humanos'), ('CONTABILIDAD', 'Contabilidad'), ('INFORMATICA', 'Informática'), ('OPERACIONES', 'Operaciones'), ('OTRO', 'Otro')], max_length=100, verbose_name='departamento')),
                ('foto', models.ImageField(null=True, upload_to='fotos/', verbose_name='fotografía')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
